import SwiftUI
import StoreKit

struct AboutView: View {
    @State private var showCopiedToast = false
    @State private var attestStatus: AttestStatus = .notAvailable

    private var appVersion: String {
        Bundle.main.infoDictionary?["CFBundleShortVersionString"] as? String ?? "Unknown"
    }

    private var buildNumber: String {
        Bundle.main.infoDictionary?["CFBundleVersion"] as? String ?? "0"
    }

    var body: some View {
        Form {
            // Header
            Section {
                HStack {
                    Spacer()
                    VStack(spacing: 12) {
                        Image("MiniAppIcon")
                            .resizable()
                            .scaledToFit()
                            .frame(width: 60, height: 60)
                            .clipShape(RoundedRectangle(cornerRadius: 14, style: .continuous))
                            .shadow(color: Color.black.opacity(0.1), radius: 2, x: 0, y: 1)

                        Text("Watch My Calories")
                            .font(.headline)
                            .foregroundStyle(Color.cwPrimary)

                        Button {
                            UIPasteboard.general.string = "Version \(appVersion) (\(buildNumber))"
                            showCopiedToast = true
                            DispatchQueue.main.asyncAfter(deadline: .now() + 1.5) {
                                showCopiedToast = false
                            }
                        } label: {
                            if showCopiedToast {
                                Text("Copied!")
                                    .font(.caption)
                                    .foregroundStyle(Color.cwPrimary)
                            } else {
                                Text("Version \(appVersion) (\(buildNumber))")
                                    .font(.caption)
                                    .foregroundStyle(.secondary)
                            }
                        }
                        .accessibilityIdentifier(AccessibilityID.About.versionLabel)
                    }
                    Spacer()
                }
                .listRowBackground(Color.clear)
            }

            // Ad
            Section {
                BannerAdView()
                    .listRowInsets(EdgeInsets())
                    .listRowBackground(Color.clear)
            }

            // Rate
            Section {
                Button {
                    if let scene = UIApplication.shared.connectedScenes
                        .compactMap({ $0 as? UIWindowScene })
                        .first {
                        SKStoreReviewController.requestReview(in: scene)
                    }
                } label: {
                    Label("Rate on App Store", systemImage: "star")
                }
                .accessibilityIdentifier(AccessibilityID.About.rateOnAppStore)
            }

            // Support & Legal
            Section(header: Text("Support & Legal")) {
                Link(destination: URL(string: "https://gist.github.com/pning80/7dc8a85c83edcc03845d182386cab470")!) {
                    Label("Help & Support", systemImage: "questionmark.circle")
                }
                .accessibilityIdentifier(AccessibilityID.About.helpAndSupport)

                Link(destination: URL(string: "https://gist.github.com/pning80/fc4cc0aab367f96202371566241ec7cb")!) {
                    Label("Privacy Policy", systemImage: "hand.raised")
                }
                .accessibilityIdentifier(AccessibilityID.About.privacyPolicy)
            }

            // Device Attestation
            Section(header: Text("Device Attestation")) {
                switch attestStatus {
                case .verified:
                    Label("Verified", systemImage: "checkmark.shield.fill")
                        .foregroundStyle(.green)
                case .notVerified:
                    Label("Not Verified", systemImage: "shield.slash")
                        .foregroundStyle(.secondary)
                case .notAvailable:
                    Label("Not Available", systemImage: "shield.slash")
                        .foregroundStyle(.secondary)
                }
            }

            // Footer
            Section {
                VStack(spacing: 8) {
                    Text("Calorie estimates are generated by AI and may not be accurate. Not intended as medical or nutritional advice.")
                        .font(.caption)
                        .foregroundStyle(.secondary)
                        .multilineTextAlignment(.center)

                    Text("Powered by Google Gemini")
                        .font(.caption)
                        .foregroundStyle(.secondary)

                    Text("© 2026 Watch My Calories")
                        .font(.caption2)
                        .foregroundStyle(.tertiary)
                }
                .frame(maxWidth: .infinity)
                .listRowBackground(Color.clear)
            }
        }
        .navigationTitle("About")
        .navigationBarTitleDisplayMode(.inline)
        .onAppear {
            let manager = AppAttestManager.shared
            if manager.isSupported {
                attestStatus = manager.isAttested() ? .verified : .notVerified
            } else {
                attestStatus = .notAvailable
            }
        }
    }
}

private enum AttestStatus {
    case verified, notVerified, notAvailable
}
