package com.pning80.watchmycalories.ui.photolib

import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.layout.size
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.AutoAwesome
import androidx.compose.material3.Button
import androidx.compose.material3.ExperimentalMaterial3Api
import androidx.compose.material3.Icon
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.ModalBottomSheet
import androidx.compose.material3.Switch
import androidx.compose.material3.Text
import androidx.compose.material3.rememberModalBottomSheetState
import androidx.compose.runtime.Composable
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.setValue
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.platform.testTag
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.style.TextAlign
import androidx.compose.ui.unit.dp
import com.pning80.watchmycalories.ui.theme.Spacing
import com.pning80.watchmycalories.utils.AccessibilityTags

/**
 * One-time AI-estimate disclaimer (PORTING_CRITERIA.md T1.1, parity with iOS
 * `CalorieDisclaimerSheet` in `Components.swift`). Persistence of the
 * "don't show again" toggle is the caller's responsibility — see
 * `SettingsDataStore.setSeenEstimateDisclaimer`.
 */
@OptIn(ExperimentalMaterial3Api::class)
@Composable
fun CalorieDisclaimerSheet(
    onContinue: (dontShowAgain: Boolean) -> Unit,
) {
    val sheetState = rememberModalBottomSheetState(skipPartiallyExpanded = true)
    var dontShowAgain by remember { mutableStateOf(false) }

    ModalBottomSheet(
        onDismissRequest = { onContinue(dontShowAgain) },
        sheetState = sheetState,
    ) {
        Column(
            modifier = Modifier
                .fillMaxWidth()
                .padding(horizontal = Spacing.xxl, vertical = Spacing.l),
            horizontalAlignment = Alignment.CenterHorizontally,
            verticalArrangement = Arrangement.spacedBy(Spacing.l),
        ) {
            Icon(
                // iOS uses the `sparkles` SF Symbol (AI/magic cue); AutoAwesome
                // is the Material equivalent. A plain Star reads as Rate/Favorite.
                imageVector = Icons.Filled.AutoAwesome,
                contentDescription = null,
                tint = MaterialTheme.colorScheme.primary,
                modifier = Modifier.size(48.dp),
            )

            Text(
                text = "Estimates Are Approximate",
                style = MaterialTheme.typography.titleLarge,
                fontWeight = FontWeight.Bold,
                color = MaterialTheme.colorScheme.onSurface,
            )

            Text(
                text = "Calorie and nutrition values are generated by AI and may not be perfectly accurate. " +
                    "Results can vary based on portion size, preparation method, and image quality. " +
                    "This is not medical or nutritional advice.",
                style = MaterialTheme.typography.bodyMedium,
                color = MaterialTheme.colorScheme.onSurfaceVariant,
                textAlign = TextAlign.Center,
            )

            Text(
                text = "You can always find this notice in About.",
                style = MaterialTheme.typography.bodySmall,
                color = MaterialTheme.colorScheme.outline,
                textAlign = TextAlign.Center,
            )

            Spacer(Modifier.height(Spacing.s))

            Box(modifier = Modifier.fillMaxWidth()) {
                Text(
                    text = "Don't show this again",
                    style = MaterialTheme.typography.bodyMedium,
                    modifier = Modifier.align(Alignment.CenterStart),
                )
                Switch(
                    checked = dontShowAgain,
                    onCheckedChange = { dontShowAgain = it },
                    modifier = Modifier
                        .align(Alignment.CenterEnd)
                        .testTag(AccessibilityTags.Disclaimer.DONT_SHOW_TOGGLE),
                )
            }

            Button(
                onClick = { onContinue(dontShowAgain) },
                modifier = Modifier
                    .fillMaxWidth()
                    .testTag(AccessibilityTags.Disclaimer.CONTINUE_BUTTON),
            ) {
                Text(
                    text = "Continue",
                    fontWeight = FontWeight.SemiBold,
                    modifier = Modifier.padding(vertical = Spacing.xs),
                )
            }
        }
    }
}
