package com.pning80.watchmycalories.parity

import androidx.compose.ui.test.assertHasClickAction
import androidx.compose.ui.test.assertIsDisplayed
import androidx.compose.ui.test.onAllNodesWithTag
import androidx.compose.ui.test.onAllNodesWithText
import androidx.compose.ui.test.onNodeWithTag
import androidx.compose.ui.test.onNodeWithText
import androidx.compose.ui.test.performClick
import androidx.compose.ui.test.performScrollTo
import com.pning80.watchmycalories.utils.AccessibilityTags
import org.junit.Test

/**
 * Parity mirror of iOS `WatchMyCaloriesUITests/AppMenuTests.swift`.
 *
 * iOS exposes a Today-toolbar app menu (gear icon → menu sheet with About +
 * Settings items). Android collapses this to a direct "Settings" gear icon
 * on the TopAppBar; About is reached via Settings → "About this app".
 *
 * Skipped — parity divergences:
 *   - testAppMenuShowsAllItems — Android has no menu UI; gear goes straight to
 *     Settings. This is a *flow* difference, not a feature gap.
 *   - testAboutScreenShowsAIDisclaimer — Android About does not render a
 *     "generated by AI" disclaimer string. Documented gap candidate.
 *
 * Known navigation divergence (asserted via the Android path):
 *   - iOS: gear → menu → "About" → About screen
 *   - Android: gear → Settings → "About this app" → About screen
 *
 * Known label divergence: iOS About nav-bar title is "About"; Android TopAppBar
 * title is "About Watch My Calories".
 */
class AppMenuParityTest : MainActivityComposeTest() {

    /** Open About via the Android path: gear → Settings → "About this app". */
    private fun openAbout() {
        launchEmpty()
        composeTestRule.onNodeWithTag(AccessibilityTags.AppMenu.MENU_BUTTON).performClick()
        composeTestRule.waitForIdle()
        composeTestRule.onNodeWithTag("SettingsTitle").assertIsDisplayed()
        composeTestRule.onNodeWithText("About this app").performScrollTo().performClick()
        composeTestRule.waitForIdle()
        composeTestRule.onNodeWithText("About Watch My Calories").assertIsDisplayed()
    }

    // MARK: - Menu Visibility

    /** Mirror of iOS `testAppMenuVisibleOnTodayScreen`. */
    @Test
    fun testAppMenuVisibleOnTodayScreen() {
        launchEmpty()
        composeTestRule.onNodeWithTag(AccessibilityTags.AppMenu.MENU_BUTTON).assertIsDisplayed()
    }

    /** Mirror of iOS `testAppMenuVisibleOnHistoryScreen`. */
    @Test
    fun testAppMenuVisibleOnHistoryScreen() {
        launchEmpty()
        composeTestRule.onNodeWithTag(AccessibilityTags.Tab.HISTORY).performClick()
        composeTestRule.waitForIdle()
        composeTestRule.onNodeWithTag(AccessibilityTags.AppMenu.MENU_BUTTON).assertIsDisplayed()
    }

    /** Mirror of iOS `testLogFoodTabShowsSheetNotTab`. */
    @Test
    fun testLogFoodTabShowsSheetNotTab() {
        launchEmpty()
        composeTestRule.onNodeWithTag(AccessibilityTags.Tab.CAMERA).performClick()
        composeTestRule.waitForIdle()
        // The sheet exposes "Log Manually" — stable text marker for the LogFoodSheet.
        composeTestRule.onNodeWithText("Log Manually").assertIsDisplayed()
    }

    /** Mirror of iOS `testOpenSettingsFromMenu`. */
    @Test
    fun testOpenSettingsFromMenu() {
        launchEmpty()
        composeTestRule.onNodeWithTag(AccessibilityTags.AppMenu.MENU_BUTTON).performClick()
        composeTestRule.waitForIdle()
        composeTestRule.onNodeWithTag("SettingsTitle").assertIsDisplayed()
    }

    // MARK: - About

    /** Mirror of iOS `testOpenAboutFromMenu` (Android-adapted nav path). */
    @Test
    fun testOpenAboutFromMenu() {
        openAbout()
        // Verify the About screen body contains the app name (line 60-64 in AboutScreen.kt).
        composeTestRule.onNodeWithText("Watch My Calories").assertIsDisplayed()
    }

    /** Mirror of iOS `testAboutScreenShowsHelpAndSupport`. */
    @Test
    fun testAboutScreenShowsHelpAndSupport() {
        openAbout()
        composeTestRule.onNodeWithTag(AccessibilityTags.About.HELP_AND_SUPPORT).assertIsDisplayed()
    }

    /** Mirror of iOS `testAboutScreenShowsPrivacyPolicy`. */
    @Test
    fun testAboutScreenShowsPrivacyPolicy() {
        openAbout()
        composeTestRule.onNodeWithTag(AccessibilityTags.About.PRIVACY_POLICY).assertIsDisplayed()
    }

    /** Mirror of iOS `testAboutScreenShowsRateOnAppStore`. */
    @Test
    fun testAboutScreenShowsRateOnAppStore() {
        openAbout()
        composeTestRule.onNodeWithTag(AccessibilityTags.About.RATE_ON_APP_STORE).assertIsDisplayed()
    }

    /** Mirror of iOS `testAboutScreenShowsDeviceAttestation`. */
    @Test
    fun testAboutScreenShowsDeviceAttestation() {
        openAbout()
        composeTestRule.onNodeWithText("Device Attestation").assertIsDisplayed()
        // Android renders one of "Verified" / "Not Verified" depending on Play Integrity state.
        val attestationStateVisible =
            composeTestRule.onAllNodesWithText("Verified").fetchSemanticsNodes().isNotEmpty() ||
            composeTestRule.onAllNodesWithText("Not Verified").fetchSemanticsNodes().isNotEmpty()
        assert(attestationStateVisible) {
            "About screen should expose an attestation status (Verified / Not Verified)"
        }
    }

    /** Mirror of iOS `testAboutVersionLabelExists`. */
    @Test
    fun testAboutVersionLabelExists() {
        openAbout()
        composeTestRule.onNodeWithTag(AccessibilityTags.About.VERSION_LABEL).assertIsDisplayed()
    }

    /**
     * Adapted from iOS `testAboutVersionTapCopiesToClipboard`. Android version
     * label is not yet wired with a tap-to-copy gesture; this test verifies the
     * label is present and tapping it (no-op on Android) does not break the screen.
     */
    @Test
    fun testAboutVersionLabelStableUnderTap() {
        openAbout()
        composeTestRule.onNodeWithTag(AccessibilityTags.About.VERSION_LABEL).performClick()
        composeTestRule.waitForIdle()
        composeTestRule.onNodeWithText("About Watch My Calories").assertIsDisplayed()
    }

    /** Mirror of iOS `testAboutHelpAndSupportLinkTaps`. */
    @Test
    fun testAboutHelpAndSupportLinkReachable() {
        openAbout()
        composeTestRule.onNodeWithTag(AccessibilityTags.About.HELP_AND_SUPPORT)
            .assertHasClickAction()
            .assertIsDisplayed()
    }

    /** Mirror of iOS `testAboutPrivacyPolicyLinkTaps`. */
    @Test
    fun testAboutPrivacyPolicyLinkReachable() {
        openAbout()
        composeTestRule.onNodeWithTag(AccessibilityTags.About.PRIVACY_POLICY)
            .assertHasClickAction()
            .assertIsDisplayed()
    }

    /** Mirror of iOS `testAboutRateOnAppStoreReachable`. */
    @Test
    fun testAboutRateOnAppStoreReachable() {
        openAbout()
        composeTestRule.onNodeWithTag(AccessibilityTags.About.RATE_ON_APP_STORE)
            .assertHasClickAction()
            .assertIsDisplayed()
    }

    // MARK: - Ads

    /** Mirror of iOS `testSettingsBannerAdHiddenUnderUITesting`. */
    @Test
    fun testSettingsBannerAdHiddenUnderUITesting() {
        launchEmpty()
        composeTestRule.onNodeWithTag(AccessibilityTags.AppMenu.MENU_BUTTON).performClick()
        composeTestRule.waitForIdle()
        // Banner is gated by the placeholder-ad-unit check in BannerAdView.kt and
        // by AdManager.disableForUITesting via TestSeed. Either path must keep
        // the banner testTag absent under EXTRA_UI_TESTING.
        assert(composeTestRule.onAllNodesWithTag(AccessibilityTags.Ads.BANNER).fetchSemanticsNodes().isEmpty()) {
            "ads_banner testTag should not appear in Settings under EXTRA_UI_TESTING"
        }
    }
}
