import XCTest

final class AppMenuTests: WatchMyCaloriesUITestBase {

    // MARK: - Menu Visibility

    func testAppMenuVisibleOnTodayScreen() {
        launchEmpty()

        let menuButton = app.buttons["appMenu_button"]
        XCTAssertTrue(menuButton.waitForExistence(timeout: 3))
    }

    func testAppMenuVisibleOnHistoryScreen() {
        launchEmpty()

        app.tabBars.buttons["History"].tap()

        let menuButton = app.buttons["appMenu_button"]
        XCTAssertTrue(menuButton.waitForExistence(timeout: 3))
    }

    func testLogFoodTabShowsSheetNotTab() {
        launchEmpty()

        app.tabBars.buttons["Log Food"].tap()

        // Log Food shows a sheet, not a tab
        XCTAssertTrue(app.staticTexts["Log Food"].waitForExistence(timeout: 3))
    }

    // MARK: - Menu Items

    func testAppMenuShowsAllItems() {
        launchEmpty()

        let menuButton = app.buttons["appMenu_button"]
        XCTAssertTrue(menuButton.waitForExistence(timeout: 3))
        menuButton.tap()

        XCTAssertTrue(app.buttons["About"].waitForExistence(timeout: 3))
        XCTAssertTrue(app.buttons["Settings"].exists)
    }

    // MARK: - Open About

    func testOpenAboutFromMenu() {
        launchEmpty()

        app.buttons["appMenu_button"].tap()
        app.buttons["About"].tap()

        XCTAssertTrue(app.navigationBars["About"].waitForExistence(timeout: 3))

        // Verify key content
        XCTAssertTrue(app.staticTexts["Watch My Calories"].exists)

        // Dismiss
        app.buttons["Done"].tap()
        XCTAssertTrue(app.buttons["dashboard_emptyStateCard"].waitForExistence(timeout: 3))
    }

    func testAboutScreenShowsAIDisclaimer() {
        launchEmpty()

        app.buttons["appMenu_button"].tap()
        app.buttons["About"].tap()

        XCTAssertTrue(app.navigationBars["About"].waitForExistence(timeout: 3))

        app.swipeUp()

        let disclaimer = app.staticTexts.containing(NSPredicate(format: "label CONTAINS %@", "generated by AI"))
        XCTAssertTrue(disclaimer.firstMatch.waitForExistence(timeout: 3))
    }

    func testAboutScreenShowsHelpAndSupport() {
        launchEmpty()

        app.buttons["appMenu_button"].tap()
        app.buttons["About"].tap()

        XCTAssertTrue(app.navigationBars["About"].waitForExistence(timeout: 3))

        let helpLink = app.buttons["about_helpAndSupport"]
        XCTAssertTrue(helpLink.waitForExistence(timeout: 3))
    }

    func testAboutScreenShowsPrivacyPolicy() {
        launchEmpty()

        app.buttons["appMenu_button"].tap()
        app.buttons["About"].tap()

        XCTAssertTrue(app.navigationBars["About"].waitForExistence(timeout: 3))

        let privacyLink = app.buttons["about_privacyPolicy"]
        XCTAssertTrue(privacyLink.waitForExistence(timeout: 3))
    }

    func testAboutScreenShowsRateOnAppStore() {
        launchEmpty()

        app.buttons["appMenu_button"].tap()
        app.buttons["About"].tap()

        XCTAssertTrue(app.navigationBars["About"].waitForExistence(timeout: 3))

        let rateButton = app.buttons["about_rateOnAppStore"]
        XCTAssertTrue(rateButton.waitForExistence(timeout: 3))
    }

    func testAboutScreenShowsDeviceAttestation() {
        launchEmpty()

        app.buttons["appMenu_button"].tap()
        app.buttons["About"].tap()

        XCTAssertTrue(app.navigationBars["About"].waitForExistence(timeout: 3))

        app.swipeUp()

        // Attestation shows as Verified, Not Verified, or Not Available
        let attestLabel = app.staticTexts.containing(NSPredicate(format: "label CONTAINS %@ OR label CONTAINS %@ OR label CONTAINS %@", "Verified", "Not Verified", "Not Available"))
        XCTAssertTrue(attestLabel.firstMatch.waitForExistence(timeout: 3))
    }

    // MARK: - Open Settings

    func testOpenSettingsFromMenu() {
        launchEmpty()

        app.buttons["appMenu_button"].tap()
        app.buttons["Settings"].tap()

        XCTAssertTrue(app.navigationBars["Settings"].waitForExistence(timeout: 3))
    }
}
