import XCTest

final class AppMenuTests: WatchMyCaloriesUITestBase {

    // MARK: - Menu Visibility

    func testAppMenuVisibleOnTodayScreen() {
        launchEmpty()

        let menuButton = app.buttons["appMenu_button"]
        XCTAssertTrue(menuButton.waitForExistence(timeout: 3))
    }

    func testAppMenuVisibleOnHistoryScreen() {
        launchEmpty()

        app.tabBars.buttons["History"].tap()

        let menuButton = app.buttons["appMenu_button"]
        XCTAssertTrue(menuButton.waitForExistence(timeout: 3))
    }

    func testAppMenuNotVisibleOnScanFoodTab() {
        launchEmpty()

        app.tabBars.buttons["Scan Food"].tap()

        let menuButton = app.buttons["appMenu_button"]
        XCTAssertFalse(menuButton.waitForExistence(timeout: 2))
    }

    func testAppMenuNotVisibleOnScanMenuTab() {
        launchEmpty()

        app.tabBars.buttons["Scan Menu"].tap()

        let menuButton = app.buttons["appMenu_button"]
        XCTAssertFalse(menuButton.waitForExistence(timeout: 2))
    }

    // MARK: - Menu Items

    func testAppMenuShowsAllItems() {
        launchEmpty()

        let menuButton = app.buttons["appMenu_button"]
        XCTAssertTrue(menuButton.waitForExistence(timeout: 3))
        menuButton.tap()

        XCTAssertTrue(app.buttons["Scanned Menus"].waitForExistence(timeout: 3))
        XCTAssertTrue(app.buttons["About"].exists)
        XCTAssertTrue(app.buttons["Settings"].exists)
    }

    // MARK: - Open Scanned Menus

    func testOpenScannedMenusFromMenu() {
        launchEmpty()

        app.buttons["appMenu_button"].tap()
        app.buttons["Scanned Menus"].tap()

        // Should show ScannedMenusView as a sheet
        XCTAssertTrue(app.navigationBars["Scanned Menus"].waitForExistence(timeout: 3))

        // Should show empty state
        XCTAssertTrue(app.staticTexts.containing(NSPredicate(format: "label CONTAINS %@", "No scanned menus")).firstMatch.waitForExistence(timeout: 3))

        // Dismiss
        app.buttons["Done"].tap()
        XCTAssertTrue(app.buttons["dashboard_addButton"].waitForExistence(timeout: 3))
    }

    // MARK: - Open About

    func testOpenAboutFromMenu() {
        launchEmpty()

        app.buttons["appMenu_button"].tap()
        app.buttons["About"].tap()

        XCTAssertTrue(app.navigationBars["About"].waitForExistence(timeout: 3))

        // Verify key content
        XCTAssertTrue(app.staticTexts["Watch My Calories"].exists)

        // Dismiss
        app.buttons["Done"].tap()
        XCTAssertTrue(app.buttons["dashboard_addButton"].waitForExistence(timeout: 3))
    }

    func testAboutScreenShowsAIDisclaimer() {
        launchEmpty()

        app.buttons["appMenu_button"].tap()
        app.buttons["About"].tap()

        XCTAssertTrue(app.navigationBars["About"].waitForExistence(timeout: 3))

        app.swipeUp()

        let disclaimer = app.staticTexts.containing(NSPredicate(format: "label CONTAINS %@", "generated by AI"))
        XCTAssertTrue(disclaimer.firstMatch.waitForExistence(timeout: 3))
    }

    func testAboutScreenShowsHelpAndSupport() {
        launchEmpty()

        app.buttons["appMenu_button"].tap()
        app.buttons["About"].tap()

        XCTAssertTrue(app.navigationBars["About"].waitForExistence(timeout: 3))

        let helpLink = app.buttons["about_helpAndSupport"]
        XCTAssertTrue(helpLink.waitForExistence(timeout: 3))
    }

    func testAboutScreenShowsPrivacyPolicy() {
        launchEmpty()

        app.buttons["appMenu_button"].tap()
        app.buttons["About"].tap()

        XCTAssertTrue(app.navigationBars["About"].waitForExistence(timeout: 3))

        let privacyLink = app.buttons["about_privacyPolicy"]
        XCTAssertTrue(privacyLink.waitForExistence(timeout: 3))
    }

    // MARK: - Open Settings

    func testOpenSettingsFromMenu() {
        launchEmpty()

        app.buttons["appMenu_button"].tap()
        app.buttons["Settings"].tap()

        XCTAssertTrue(app.navigationBars["Settings"].waitForExistence(timeout: 3))
    }
}
